import type { Locale } from '@/lib/i18n'

// Interface copy. Written per language (not machine-translated). No em dashes.
const en = {
  tagline: 'Hotels with views worth waking up for.',
  heroA: 'Don’t just stay near it.',
  heroB: 'Wake up to it.',
  heroIn: 'Wake up with a view in',
  heroCities: ['Paris', 'London', 'Rome', 'New York', 'Barcelona', 'Lisbon', 'Venice', 'Tokyo', 'Istanbul', 'Dubai', 'Amsterdam'],
  searchQ: 'Where do you',
  searchQem: 'want to wake up?',
  searchPlaceholder: 'Eiffel Tower, Paris',
  searchDates: 'Check-in · Check-out',
  findView: 'Find the view',
  soon: 'soon',
  live: 'Live',
  moreSoon: 'More cities are on the way',
  wakeUpTo: 'Wake up to…',
  home: 'Home',
  nav: { city: 'Paris', method: 'How we verify', destinations: 'Destinations', allOf: (x: string) => `All of ${x}`, soonTitle: 'Coming soon' },
  soonPlaces: [{ country: 'United Kingdom', city: 'London' }, { country: 'Italy', city: 'Rome' }, { country: 'United States', city: 'New York' }],
  withView: 'With a view',
  nearby: 'Nearby',
  hotelsWithView: (n: number) => (n === 1 ? '1 hotel with a view' : `${n} hotels with a view`),
  view: 'view',
  from: 'from',
  checkAvailability: 'Check availability',
  seeRooms: 'See rooms & prices',
  checkPrice: 'Check current price',
  reviews: (n: string) => `${n} reviews`,
  viewNotConfirmed: 'View not confirmed',
  balcony: 'Balcony',
  terrace: 'Terrace',
  rooftop: 'Rooftop',
  yes: 'yes',
  unknown: 'not stated',
  straight: 'straight line',
  walkEst: (m: number) => `about ${m} min walk`,
  fromLm: (d: string, lm: string) => `${d} from ${lm}`,
  ctx: {
    ROOM: 'From selected rooms',
    ROOM_NAMED: 'Named in the room category',
    BALCONY: 'From room balconies',
    TERRACE: 'From a terrace',
    ROOFTOP: 'From the rooftop',
    RESTAURANT: 'From the restaurant',
    BAR: 'From the bar',
    POOL: 'From the pool',
    COMMON_AREA: 'From shared areas',
    UNKNOWN: 'Mentioned by the hotel',
  } as Record<string, string>,
  partial: 'partial view',
  alternative: 'or another landmark',
  highFloor: 'high floor',
  some: 'some rooms only',
  conf: { HIGH: 'Room-level source', MEDIUM: 'Hotel-level source' } as Record<string, string>,
  sourceLabel: 'Source wording',
  priceNote: (price: string, date: string) => `From ${price} per night on ${date}, 2 adults, collected ahead. Prices move daily.`,
  viewPrice: (price: string) => `View room from ${price}`,
  mapLegendView: 'Hotels with a view',
  mapLegendNear: 'Nearby hotels',
  crossToNear: 'Just need to be close?',
  crossToNearCta: (lm: string) => `See hotels near ${lm}`,
  crossToView: 'Want the view too?',
  crossToViewCta: (lm: string) => `See hotels with ${lm} views`,
  nearbyLandmarks: 'Nearby landmarks',
  goodToKnow: 'Good to know',
  inNumbers: 'The view in numbers',
  whatsNearby: 'What’s nearby',
  views: 'Views',
  amenities: 'Amenities',
  address: 'Address',
  lastChecked: (d: string) => `Last checked ${d}`,
  footerNote: 'A view is listed only when a room name or the hotel’s own description mentions it. Bookings are made with our partners, who may pay us a commission.',
  footerIndependent: 'Independent guide.',
  noindexNote: 'We are still collecting hotels for this view. This page stays out of search results until the list is solid.',
  breadcrumbCity: 'Paris',
  countryH1: (c: string) => `Hotels with a view in ${c}`,
  countryLede: (c: string) => `Choose a city, then the landmark you want to wake up to. We add cities in ${c} only when their views are checked.`,
  citiesIn: (c: string) => `Cities in ${c}`,
  landmarksIn: 'Landmarks',
  hotelsIn: 'Hotels',
  viewFrom: 'Where the view comes from',
  also: 'This hotel also looks at',
  seeAll: 'See all',
  whatToWakeUp: 'What do you want to wake up to?',
  cityHotelsWithView: 'Paris hotels with a view, by landmark',
  stayNear: 'Stay near Paris landmarks',
  hotelsNear: (lm: string) => `Hotels near ${lm}`,
  sortedByDistance: 'Sorted by distance: straight line first, walking time estimated.',
  withinKm: (n: number, km: string) => `${n} rated hotels within ${km}`,
  hasView: 'View confirmed',
  langLabel: 'Language',
  methodLink: 'How we verify views',
  bookCta: 'Search all Paris hotels around this landmark',
  photoNote: 'Photo: hotel listing. A photo illustrates, it does not prove a view.',
}

export type UI = typeof en

const es: UI = {
  tagline: 'Hoteles con vistas por las que merece la pena despertarse.',
  heroA: 'No te quedes solo cerca.',
  heroB: 'Despierta frente a ella.',
  heroIn: 'Despierta con vistas en',
  heroCities: ['París', 'Londres', 'Roma', 'Nueva York', 'Barcelona', 'Lisboa', 'Venecia', 'Tokio', 'Estambul', 'Dubái', 'Ámsterdam'],
  searchQ: '¿Dónde quieres',
  searchQem: 'despertarte?',
  searchPlaceholder: 'Torre Eiffel, París',
  searchDates: 'Entrada · Salida',
  findView: 'Buscar la vista',
  soon: 'pronto',
  live: 'Disponible',
  moreSoon: 'Pronto, más ciudades',
  wakeUpTo: 'Despierta frente a…',
  home: 'Inicio',
  nav: { city: 'París', method: 'Cómo verificamos', destinations: 'Destinos', allOf: (x) => `Todo ${x}`, soonTitle: 'Próximamente' },
  soonPlaces: [{ country: 'Reino Unido', city: 'Londres' }, { country: 'Italia', city: 'Roma' }, { country: 'Estados Unidos', city: 'Nueva York' }],
  withView: 'Con vistas',
  nearby: 'Cerca',
  hotelsWithView: (n) => (n === 1 ? '1 hotel con vistas' : `${n} hoteles con vistas`),
  view: 'vistas',
  from: 'desde',
  checkAvailability: 'Ver disponibilidad',
  seeRooms: 'Ver habitaciones y precios',
  checkPrice: 'Consultar precio actual',
  reviews: (n) => `${n} opiniones`,
  viewNotConfirmed: 'Vistas sin confirmar',
  balcony: 'Balcón',
  terrace: 'Terraza',
  rooftop: 'Azotea',
  yes: 'sí',
  unknown: 'sin datos',
  straight: 'en línea recta',
  walkEst: (m) => `unos ${m} min a pie`,
  fromLm: (d, lm) => `a ${d} de ${lm}`,
  ctx: {
    ROOM: 'Desde algunas habitaciones',
    ROOM_NAMED: 'Indicado en el tipo de habitación',
    BALCONY: 'Desde los balcones',
    TERRACE: 'Desde una terraza',
    ROOFTOP: 'Desde la azotea',
    RESTAURANT: 'Desde el restaurante',
    BAR: 'Desde el bar',
    POOL: 'Desde la piscina',
    COMMON_AREA: 'Desde zonas comunes',
    UNKNOWN: 'Lo menciona el hotel',
  },
  partial: 'vista parcial',
  alternative: 'u otro monumento',
  highFloor: 'planta alta',
  some: 'solo algunas habitaciones',
  conf: { HIGH: 'Fuente: tipo de habitación', MEDIUM: 'Fuente: descripción del hotel' },
  sourceLabel: 'Texto original',
  priceNote: (price, date) => `Desde ${price} por noche el ${date}, 2 adultos, consultado con antelación. Los precios cambian a diario.`,
  viewPrice: (price) => `Habitación con vistas desde ${price}`,
  mapLegendView: 'Hoteles con vistas',
  mapLegendNear: 'Hoteles cercanos',
  crossToNear: '¿Solo necesitas estar cerca?',
  crossToNearCta: (lm) => `Ver hoteles cerca de ${lm}`,
  crossToView: '¿También quieres las vistas?',
  crossToViewCta: (lm) => `Ver hoteles con vistas a ${lm}`,
  nearbyLandmarks: 'Monumentos cercanos',
  goodToKnow: 'Conviene saber',
  inNumbers: 'Las vistas en cifras',
  whatsNearby: 'Qué hay cerca',
  views: 'Vistas',
  amenities: 'Servicios',
  address: 'Dirección',
  lastChecked: (d) => `Última comprobación: ${d}`,
  footerNote: 'Solo indicamos unas vistas cuando el nombre de la habitación o la descripción del propio hotel las menciona. Las reservas se hacen con nuestros socios, que pueden pagarnos una comisión.',
  footerIndependent: 'Guía independiente.',
  noindexNote: 'Seguimos reuniendo hoteles para estas vistas. Esta página no aparecerá en los buscadores hasta que la lista sea sólida.',
  breadcrumbCity: 'París',
  countryH1: (c) => `Hoteles con vistas en ${c}`,
  countryLede: (c) => `Elige una ciudad y luego el monumento frente al que quieres despertarte. Solo añadimos ciudades de ${c} cuando sus vistas están verificadas.`,
  citiesIn: (c) => `Ciudades de ${c}`,
  landmarksIn: 'Monumentos',
  hotelsIn: 'Hoteles',
  viewFrom: 'Desde dónde se ve',
  also: 'Este hotel también tiene vistas a',
  seeAll: 'Ver todo',
  whatToWakeUp: '¿Frente a qué quieres despertarte?',
  cityHotelsWithView: 'Hoteles de París con vistas, por monumento',
  stayNear: 'Alojarse cerca de los monumentos de París',
  hotelsNear: (lm) => `Hoteles cerca de ${lm}`,
  sortedByDistance: 'Ordenados por distancia: primero en línea recta, con el tiempo a pie estimado.',
  withinKm: (n, km) => `${n} hoteles con valoración a menos de ${km}`,
  hasView: 'Vistas confirmadas',
  langLabel: 'Idioma',
  methodLink: 'Cómo verificamos las vistas',
  bookCta: 'Buscar todos los hoteles de París en torno a este monumento',
  photoNote: 'Foto: ficha del hotel. Una foto ilustra, no demuestra unas vistas.',
}

const de: UI = {
  tagline: 'Hotels mit Aussichten, für die sich das Aufwachen lohnt.',
  heroA: 'Nicht nur in der Nähe wohnen.',
  heroB: 'Mit Blick darauf aufwachen.',
  heroIn: 'Mit Aussicht aufwachen in',
  heroCities: ['Paris', 'London', 'Rom', 'New York', 'Barcelona', 'Lissabon', 'Venedig', 'Tokio', 'Istanbul', 'Dubai', 'Amsterdam'],
  searchQ: 'Wo möchtest du',
  searchQem: 'aufwachen?',
  searchPlaceholder: 'Eiffelturm, Paris',
  searchDates: 'Anreise · Abreise',
  findView: 'Aussicht finden',
  soon: 'bald',
  live: 'Online',
  moreSoon: 'Weitere Städte folgen',
  wakeUpTo: 'Aufwachen mit Blick auf…',
  home: 'Start',
  nav: { city: 'Paris', method: 'So prüfen wir', destinations: 'Reiseziele', allOf: (x) => `Ganz ${x}`, soonTitle: 'Demnächst' },
  soonPlaces: [{ country: 'Großbritannien', city: 'London' }, { country: 'Italien', city: 'Rom' }, { country: 'USA', city: 'New York' }],
  withView: 'Mit Aussicht',
  nearby: 'In der Nähe',
  hotelsWithView: (n) => (n === 1 ? '1 Hotel mit Aussicht' : `${n} Hotels mit Aussicht`),
  view: 'Blick',
  from: 'ab',
  checkAvailability: 'Verfügbarkeit prüfen',
  seeRooms: 'Zimmer und Preise ansehen',
  checkPrice: 'Aktuellen Preis prüfen',
  reviews: (n) => `${n} Bewertungen`,
  viewNotConfirmed: 'Aussicht nicht bestätigt',
  balcony: 'Balkon',
  terrace: 'Terrasse',
  rooftop: 'Dachterrasse',
  yes: 'ja',
  unknown: 'keine Angabe',
  straight: 'Luftlinie',
  walkEst: (m) => `etwa ${m} Min. zu Fuß`,
  fromLm: (d, lm) => `${d} vom ${lm}`,
  ctx: {
    ROOM: 'Aus ausgewählten Zimmern',
    ROOM_NAMED: 'In der Zimmerkategorie genannt',
    BALCONY: 'Vom Zimmerbalkon',
    TERRACE: 'Von einer Terrasse',
    ROOFTOP: 'Von der Dachterrasse',
    RESTAURANT: 'Vom Restaurant',
    BAR: 'Von der Bar',
    POOL: 'Vom Pool',
    COMMON_AREA: 'Aus Gemeinschaftsbereichen',
    UNKNOWN: 'Vom Hotel erwähnt',
  },
  partial: 'Teilblick',
  alternative: 'oder ein anderes Wahrzeichen',
  highFloor: 'obere Etage',
  some: 'nur einige Zimmer',
  conf: { HIGH: 'Quelle: Zimmerkategorie', MEDIUM: 'Quelle: Hotelbeschreibung' },
  sourceLabel: 'Originalwortlaut',
  priceNote: (price, date) => `Ab ${price} pro Nacht am ${date}, 2 Erwachsene, vorab erhoben. Preise ändern sich täglich.`,
  viewPrice: (price) => `Zimmer mit Blick ab ${price}`,
  mapLegendView: 'Hotels mit Aussicht',
  mapLegendNear: 'Hotels in der Nähe',
  crossToNear: 'Hauptsache in der Nähe?',
  crossToNearCta: (lm) => `Hotels in der Nähe: ${lm}`,
  crossToView: 'Lieber auch mit Aussicht?',
  crossToViewCta: (lm) => `Hotels mit Blick: ${lm}`,
  nearbyLandmarks: 'Sehenswürdigkeiten in der Nähe',
  goodToKnow: 'Gut zu wissen',
  inNumbers: 'Die Aussicht in Zahlen',
  whatsNearby: 'Was ist in der Nähe',
  views: 'Aussichten',
  amenities: 'Ausstattung',
  address: 'Adresse',
  lastChecked: (d) => `Zuletzt geprüft am ${d}`,
  footerNote: 'Eine Aussicht wird nur genannt, wenn der Zimmername oder die Beschreibung des Hotels sie erwähnt. Buchungen laufen über Partner, die uns eine Provision zahlen können.',
  footerIndependent: 'Unabhängiger Ratgeber.',
  noindexNote: 'Für diese Aussicht sammeln wir noch Hotels. Die Seite bleibt aus den Suchergebnissen, bis die Liste belastbar ist.',
  breadcrumbCity: 'Paris',
  countryH1: (c) => `Hotels mit Aussicht in ${c}`,
  countryLede: (c) => `Wähle eine Stadt und dann das Wahrzeichen, auf das du morgens blicken möchtest. Städte in ${c} kommen erst dazu, wenn ihre Aussichten geprüft sind.`,
  citiesIn: (c) => `Städte in ${c}`,
  landmarksIn: 'Wahrzeichen',
  hotelsIn: 'Hotels',
  viewFrom: 'Woher der Blick kommt',
  also: 'Dieses Hotel blickt außerdem auf',
  seeAll: 'Alle ansehen',
  whatToWakeUp: 'Worauf möchtest du morgens blicken?',
  cityHotelsWithView: 'Pariser Hotels mit Aussicht, nach Wahrzeichen',
  stayNear: 'In der Nähe der Pariser Wahrzeichen übernachten',
  hotelsNear: (lm) => `Hotels in der Nähe: ${lm}`,
  sortedByDistance: 'Nach Entfernung sortiert: Luftlinie, dazu geschätzte Gehzeit.',
  withinKm: (n, km) => `${n} bewertete Hotels im Umkreis von ${km}`,
  hasView: 'Aussicht bestätigt',
  langLabel: 'Sprache',
  methodLink: 'So prüfen wir Aussichten',
  bookCta: 'Alle Pariser Hotels rund um dieses Wahrzeichen suchen',
  photoNote: 'Foto: Hotelangebot. Ein Foto illustriert, es beweist keine Aussicht.',
}

export const UI_COPY: Record<Locale, UI> = { en, es, de }
export const ui = (l: Locale) => UI_COPY[l]
